on:
  workflow_dispatch:
    # inputs:
    #   tag-name:
    #     description: "The git tag name to bump the formula to"
    #     required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update formula
        id: formula
        run: bash make-formula.sh
      - uses: peter-evans/create-pull-request@v4.2.0
        with:
          title: "Update 'ffizer' formula (${{ steps.formula.outputs.version }})"
          commit-message: ":arrow_up: update formula for ffizer@${{ steps.formula.outputs.version }}"
          branch: "update-formula/ffizer-${{ steps.formula.outputs.version }}"
