on:
  workflow_dispatch:
    # inputs:
    #   tag-name:
    #     description: "The git tag name to bump the formula to"
    #     required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: xsc/homebrew-import-release-action@v2
        id: formula
        with:
          template: HomebrewFormula/ffizer-bin.template.rb
          target: HomebrewFormula/ffizer-bin.rb
          repository: ffizer/ffizer
          asset-selector: -x86_64-apple-darwin.tar.gz
          alt-asset-selector: -x86_64-unknown-linux-gnu.tar.gz
          # tag: ${{ github.event.inputs.tag-name }}
      - uses: peter-evans/create-pull-request@v3
        with:
          title: "Update 'into-docker' formula (${{ steps.formula.outputs.version }})"
          commit-message: "Formula: into-docker@${{ steps.formula.outputs.version }}"
          branch: "update-formula/into-docker-${{ steps.formula.outputs.version }}"
